site_name: Life Applicaiton Suite
site_url: https://docs.las.com
nav:
  - Home: index.md
  - SDK:
    - Objects:
      - Command:
        - Command class: SDK docs/Classes/Command/Command.md
        - Functions:
          - getKey ( ): SDK docs/Classes/Command/getKey.md
          - getyDescription ( ): SDK docs/Classes/Command/getDescription.md
          - execute ( ): SDK docs/Classes/Command/execute.md
      - Version: SDK docs/Classes/Information/version.md
      - ModuleInfo: SDK docs/Classes/Information/moduleInfo.md
    - Namespaces:
      - Command Helper: 
        - pair ( ) : SDK docs/Namespaces/CommandHelper/pair.md
        - pairNormal ( ) : SDK docs/Namespaces/CommandHelper/pairNormal.md
        - pairInvalidArgument ( ) : SDK docs/Namespaces/CommandHelper/pairInvalidArgument.md
        - pairErrorWithMessage ( ) : SDK docs/Namespaces/CommandHelper/pairErrorWithMessage.md
        - stringValueTrue ( ) : SDK docs/Namespaces/CommandHelper/stringValueTrue.md
        - stringValueFalse ( ) : SDK docs/Namespaces/CommandHelper/stringValueFalse.md
      - Text Manipulation:
        - ensureSlash( ) : SDK docs/Namespaces/TextManip/ensureSlash.md
        - ensureNoSpaces( ) : SDK docs/Namespaces/TextManip/ensureNoSpaces.md
        - ensureAlNumNoSpaces( ) : SDK docs/Namespaces/TextManip/ensureAlNumNoSpaces.md
        - ensureNewline( ) : SDK docs/Namespaces/TextManip/ensureNewline.md

markdown_extensions:
  - toc:
      permalink: true
theme:
  name: material
  palette:
    # Automatic brightness mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: blue
      accent: green
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    # Toggle Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.prune
extra:
  version:
    provider: mike
    default: stable
